name: Verify

on:
  merge_group:
  check_suite:
    types: [completed,requested,rerequested]
  pull_request:
    branches:
      - main
      - master

jobs:
  verify:
    runs-on: ubuntu-latest
    name: Check that the presentations.yaml is syntactically correct
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20.7'
      - run: go run cmd/main.go verify --file presentations.yaml